name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v14
    with:
      force: ${{ github.event.inputs.force }}
      languages: |-
        - go: ./go-client-sdk
        - java: ./java-client-sdk
        - php: ./php-client-sdk
        - python: ./python-client-sdk
        - typescript: ./typescript-client-sdk
      mode: pr
      openapi_docs: |
        - https://raw.githubusercontent.com/speakeasy-api/openapi-directory/main/APIs/1password.com/events/1.0.0/openapi.yaml
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_PROD_API_KEY }}
